services:
  facefusion.v2:
    container_name: facefusion-nvidia-docker
    image: flori/facefusion-nvidia-docker:latest
    restart: always
    build:
      context: .
      args:
        FACEFUSION_VERSION: "2.0.0"
    ports:
      - "7862:7860"
    volumes:
      - facefusion_v2_data:/home/appuser/facefusion
    deploy:
      resources:
        limits:
          memory: "8G"
        reservations:
          memory: "256m"
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu, video ]

volumes:
  facefusion_v2_data:
    external: true
